# Generated by Django 2.0.2 on 2018-02-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='author',
            new_name='added_by',
        ),
    ]
